---
- name: collect /var/log/sfiles, ssh configs etc.
  shell: |
      mkdir -p /tmp/{{ inventory_hostname }};
      find /var/log/sfiles /etc/ssh/ \
      -maxdepth {{ other.max.depth | default(4) }} -type f -size -1024M \
      -exec cp -rL --parents {} /tmp/{{ inventory_hostname }} \;
      journalctl -x > /tmp/{{ inventory_hostname }}/journal.log;
      journalctl -xk > /tmp/{{ inventory_hostname }}/journal_kernel.log;
      find /tmp/{{ inventory_hostname }} -type d -print0 | xargs -0 chmod 755;
      find /tmp/{{ inventory_hostname }} -type f -print0 | xargs -0 chmod 644;
  ignore_errors: true
  tags: collect_hypervisor_logs
